# Generated by Django 2.1.7 on 2019-03-02 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berriedtreasureapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Entry',
        ),
    ]
