# Generated by Django 2.1.7 on 2019-03-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berriedtreasureapp', '0002_auto_20190301_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
