# Generated by Django 2.1.7 on 2019-03-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berriedtreasureapp', '0003_auto_20190301_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='comment',
            field=models.TextField(max_length=80),
        ),
    ]
